import { Clock } from "widgets/clock.slint";
import { BellIcon, NotificationTray, Notification } from "widgets/notifications.slint";

export { Notification }

export component MainWindow inherits Window {
    height: 440px;
    background: transparent;
    always-on-top: true;
    no-frame: true;

    // Propiedades compartidas (Widgets)
    in-out property <string> time-text: "--:--:--";
    in-out property <bool> has-notifications: false;
    in-out property <[Notification]> notifications: [];
    
    // Callbacks
    callback clear_all();
    callback dismiss_notif(int);

    tray := PopupWindow {
        x: parent.width - 360px;
        y: 45px;
        width: 350px;
        height: 400px;
        
        NotificationTray {
            notifications: notifications;
            clear_all => { root.clear_all(); }
            dismiss_notif(id) => { root.dismiss_notif(id); }
        }
    }

    Rectangle {
        width: 100%;
        height: 40px;
        background: @linear-gradient(180deg, rgba(26, 27, 38, 0.95) 0%, rgba(20, 20, 30, 0.98) 100%);
        y: 0;

        Rectangle {
            width: 100%;
            height: 1px;
            y: parent.height - self.height;
            background: rgba(122, 162, 247, 0.3);
        }

        HorizontalLayout {
            padding-left: 10px;
            padding-right: 10px;
            spacing: 0;
            alignment: space-between;

            // Slot Izquierdo: Branding / Launcher
            left-slot := HorizontalLayout {
                spacing: 10px;
                alignment: start;
                
                Rectangle {
                    background: rgba(122, 162, 247, 0.1);
                    border-radius: 6px;
                    HorizontalLayout {
                        padding: 8px; padding-top: 4px; padding-bottom: 4px;
                        spacing: 8px;
                        Text { text: "󱄅"; font-size: 18px; color: #7aa2f7; vertical-alignment: center; }
                        Text { text: "NixOS"; font-size: 14px; font-weight: 700; color: #c0caf5; vertical-alignment: center; }
                    }
                }
            }

            // Slot Central: Tareas / Widgets centrados
            center-slot := HorizontalLayout {
                spacing: 10px;
                alignment: center;
                
                // Aquí podrías poner el reloj si lo quieres centrado
            }

            // Slot Derecho: SysTray / Status / Clock
            right-slot := HorizontalLayout {
                spacing: 15px;
                alignment: end;
                
                BellIcon {
                    has-notifications: root.has-notifications;
                    clicked => { tray.show(); }
                }

                Clock {
                    time-text: root.time-text;
                }
            }
        }
    }
}
